# Generated by Django 5.2.11 on 2026-02-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
