# Generated by Django 5.2.11 on 2026-02-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_recipient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
    ]
