# Generated by Django 5.2.11 on 2026-03-05 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0011_review'),
        ('users', '0006_review_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'piece'), name='unique_user_piece_wishlist'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
