# Generated by Django 5.2.11 on 2026-03-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_review_piece_remove_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_piece_wishlist',
        ),
    ]
