# Generated by Django 5.2.11 on 2026-03-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_wishlist_unique_user_piece_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lista de favorito', 'verbose_name_plural': 'Lista de favoritos'},
        ),
    ]
