# Generated by Django 5.2.11 on 2026-05-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('mexico', 'MX'), ('usa', 'US'), ('canada', 'CA')], max_length=50),
        ),
    ]
