# Generated by Django 5.2.11 on 2026-05-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('mexico', 'MX'), ('usa', 'US'), ('canada', 'US')], max_length=50),
        ),
    ]
