# Generated by Django 5.2.14 on 2026-05-28 03:18

import django.core.validators
import django.db.models.deletion
import pieces.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(default='pendiente de nombrar', max_length=50)),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['percentage'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('thumbnail_path', models.ImageField(upload_to=pieces.utils.upload_pieces_thumb)),
                ('intro_video', models.FileField(blank=True, null=True, upload_to=pieces.utils.uplaod_intro_video)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_es', models.CharField(max_length=100, null=True, unique=True)),
                ('title_en', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug_es', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField()),
                ('description_es', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('customizable', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('section', models.CharField(max_length=100, unique=True)),
                ('section_es', models.CharField(max_length=100, null=True, unique=True)),
                ('section_en', models.CharField(max_length=100, null=True, unique=True)),
                ('key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('region', models.CharField(choices=[('MX', 'México'), ('US', 'Estados Unidos')], max_length=10)),
                ('kg', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Tarifa de envío',
                'verbose_name_plural': 'Tarifas de envío',
                'ordering': ['region', 'kg'],
            },
        ),
        migrations.CreateModel(
            name='TypePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('type', models.CharField(max_length=100, unique=True)),
                ('type_es', models.CharField(max_length=100, null=True, unique=True)),
                ('type_en', models.CharField(max_length=100, null=True, unique=True)),
                ('key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de pieza',
                'verbose_name_plural': 'Tipos de pieza',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='PieceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_discounts', to='pieces.discount')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='pieces.piece')),
            ],
            options={
                'verbose_name': 'Descuento por pieza',
                'verbose_name_plural': 'Descuentos por pieza',
                'ordering': ['piece'],
            },
        ),
        migrations.CreateModel(
            name='PiecePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image_path', models.ImageField(upload_to=pieces.utils.upload_piece_image)),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pieces.piece')),
            ],
            options={
                'verbose_name': 'Foto de la pieza',
                'verbose_name_plural': 'Fotos de las piezas',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('link_etsy', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=pieces.utils.upload_review_image)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces.piece')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
    ]
