# Generated by Django 5.2.14 on 2026-05-28 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pieces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piece',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='pieces.section'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('region', 'kg')},
        ),
        migrations.AddField(
            model_name='piece',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='pieces.typepiece'),
        ),
        migrations.AddConstraint(
            model_name='piecediscount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('piece',), name='unique_active_piece_discount'),
        ),
        migrations.AlterUniqueTogether(
            name='piecephoto',
            unique_together={('piece', 'position')},
        ),
    ]
