# Generated by Django 5.2.14 on 2026-06-01 20:34

from django.db import migrations


def seed_shipping_rates(apps, schema_editor):
    ShippingRate = apps.get_model('pieces', 'ShippingRate')

    rates = [
        {"kg": 1, "region": "MX", "cost": 202},
        {"kg": 2, "region": "MX", "cost": 215},
        {"kg": 3, "region": "MX", "cost": 225},
        {"kg": 4, "region": "MX", "cost": 235},
        {"kg": 5, "region": "MX", "cost": 245},
        {"kg": 6, "region": "MX", "cost": 257},
        {"kg": 7, "region": "MX", "cost": 267},
        {"kg": 8, "region": "MX", "cost": 280},
        {"kg": 9, "region": "MX", "cost": 290},
        {"kg": 10, "region": "MX", "cost": 301},
        {"kg": 11, "region": "MX", "cost": 312},
        {"kg": 12, "region": "MX", "cost": 324},
        {"kg": 13, "region": "MX", "cost": 337},
        {"kg": 14, "region": "MX", "cost": 350},
        {"kg": 15, "region": "MX", "cost": 358},

        {"kg": 1, "region": "US", "cost": 1100},
        {"kg": 2, "region": "US", "cost": 1250},
        {"kg": 3, "region": "US", "cost": 1400},
        {"kg": 4, "region": "US", "cost": 1560},
        {"kg": 5, "region": "US", "cost": 1721},
        {"kg": 6, "region": "US", "cost": 1830},
        {"kg": 7, "region": "US", "cost": 1940},
        {"kg": 8, "region": "US", "cost": 2051},
        {"kg": 9, "region": "US", "cost": 2161},
        {"kg": 10, "region": "US", "cost": 2084},
        {"kg": 11, "region": "US", "cost": 2370},
        {"kg": 12, "region": "US", "cost": 2470},
        {"kg": 13, "region": "US", "cost": 2560},
        {"kg": 14, "region": "US", "cost": 2670},
        {"kg": 15, "region": "US", "cost": 2768},
    ]

    ShippingRate.objects.bulk_create(
        [ShippingRate(**rate) for rate in rates],
        ignore_conflicts=True
    )


def unseed_shipping_rates(apps, schema_editor):
    ShippingRate = apps.get_model('pieces', 'ShippingRate')

    ShippingRate.objects.filter(
        region__in=["MX", "US"],
        kg__lte=15
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(
            seed_shipping_rates,
            reverse_code=unseed_shipping_rates
        ),
    ]