# Generated by Django 5.2.11 on 2026-02-19 21:05

import core.mixins
import django.db.models.deletion
import pieces.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0002_pieces_price_mx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail_path', models.ImageField(upload_to=pieces.utils.upload_pieces_thumb)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price_mx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lenght', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customizable', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.section')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.typepiece')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.mixins.ImagenPKMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PieceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.discount')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.piece')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PiecePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_path', models.ImageField(upload_to=pieces.utils.upload_piece_image)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.piece')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.mixins.ImagenPKMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Pieces',
        ),
    ]
