# Generated by Django 5.2.11 on 2026-02-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0003_discount_piece_piecediscount_piecephoto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='lenght',
            new_name='length',
        ),
        migrations.AddField(
            model_name='piece',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
