# Generated by Django 5.2.11 on 2026-02-20 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0004_rename_lenght_piece_length_piece_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piecediscount',
            options={},
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddConstraint(
            model_name='piecediscount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('piece',), name='unique_active_piece_discount'),
        ),
    ]
