# Generated by Django 5.2.11 on 2026-02-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0005_alter_piecediscount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='pieces.section'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='pieces.typepiece'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='piecediscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_discounts', to='pieces.discount'),
        ),
        migrations.AlterField(
            model_name='piecediscount',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='pieces.piece'),
        ),
        migrations.AlterField(
            model_name='piecephoto',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pieces.piece'),
        ),
        migrations.AlterField(
            model_name='section',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
