# Generated by Django 5.2.12 on 2026-06-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0005_auto_20260601_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='slug_es',
        ),
    ]
