# Generated by Django 5.2.11 on 2026-02-23 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0006_alter_piece_section_alter_piece_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['percentage'], 'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'verbose_name': 'Pieza', 'verbose_name_plural': 'Piezas'},
        ),
        migrations.AlterModelOptions(
            name='piecediscount',
            options={'ordering': ['piece'], 'verbose_name': 'Descuento por pieza', 'verbose_name_plural': 'Descuentos por pieza'},
        ),
        migrations.AlterModelOptions(
            name='piecephoto',
            options={'ordering': ['position'], 'verbose_name': 'Foto de la pieza', 'verbose_name_plural': 'Fotos de las piezas'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section'], 'verbose_name': 'Seccion', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterModelOptions(
            name='typepiece',
            options={'ordering': ['type'], 'verbose_name': 'Tipo de pieza', 'verbose_name_plural': 'Tipos de pieza'},
        ),
        migrations.AddField(
            model_name='piecephoto',
            name='position',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='piecephoto',
            unique_together={('piece', 'position')},
        ),
    ]
