# Generated by Django 5.2.11 on 2026-02-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0007_alter_discount_options_alter_piece_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='price_mx',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='price_usa',
        ),
        migrations.AddField(
            model_name='piece',
            name='price_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
