# Generated by Django 5.2.11 on 2026-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0008_remove_piece_price_mx_remove_piece_price_usa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.CharField(choices=[('MX', 'México'), ('USA', 'Estados Unidos')], max_length=10)),
                ('kg', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Tarifa de envío',
                'verbose_name_plural': 'Tarifas de envío',
                'ordering': ['region', 'kg'],
                'unique_together': {('region', 'kg')},
            },
        ),
    ]
