# Generated by Django 5.2.11 on 2026-03-04 16:59

import pieces.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0009_shippingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='pendiente de nombrar', max_length=50),
        ),
        migrations.AddField(
            model_name='piece',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to=pieces.utils.uplaod_intro_video),
        ),
    ]
