# Generated by Django 5.2.11 on 2026-03-05 20:42

import pieces.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pieces.utils.upload_review_image),
        ),
    ]
