# Generated by Django 5.2.11 on 2026-04-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0012_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
