# Generated by Django 5.2.11 on 2026-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0013_alter_piece_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='region',
            field=models.CharField(choices=[('MX', 'México'), ('US', 'Estados Unidos')], max_length=10),
        ),
    ]
