# Generated by Django 5.2.14 on 2026-05-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0015_alter_discount_created_at_alter_discount_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='slug_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='slug_es',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='title_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='typepiece',
            name='type_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='typepiece',
            name='type_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
