# Generated by Django 5.2.14 on 2026-05-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0016_piece_description_en_piece_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='link_etsy',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pieces.piece'),
        ),
    ]
