# Generated by Django 5.2.14 on 2026-05-28 03:18

import cms.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('name_es', models.CharField(max_length=150, null=True, unique=True)),
                ('name_en', models.CharField(max_length=150, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('thumbnail_path', models.ImageField(upload_to=cms.utils.upload_image_collection)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Coleccion',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('carousel', models.IntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero')])),
                ('position', models.IntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto')])),
                ('img', models.ImageField(upload_to=cms.utils.upload_image_carousel, validators=[cms.utils.validate_image_format])),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carruseles',
                'unique_together': {('carousel', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image_path', models.ImageField(upload_to=cms.utils.upload_image_collection)),
                ('year', models.PositiveSmallIntegerField(validators=[cms.utils.validate_year])),
                ('name', models.CharField(max_length=150)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.collection')),
            ],
            options={
                'verbose_name': 'Imagen de coleccion',
                'verbose_name_plural': 'Imagenes de colecciones',
                'indexes': [models.Index(fields=['collection', 'year'], name='imgcol_collection_year_idx')],
            },
        ),
    ]
