# Generated by Django 5.2.12 on 2026-06-08 20:18

import cms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[cms.utils.validate_year]),
        ),
    ]
