# Generated by Django 5.2.11 on 2026-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={},
        ),
        migrations.AlterField(
            model_name='carousel',
            name='position',
            field=models.IntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto')]),
        ),
        migrations.AlterUniqueTogether(
            name='carousel',
            unique_together={('carousel', 'position')},
        ),
    ]
