# Generated by Django 5.2.11 on 2026-03-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_carousel_options_alter_carousel_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
