# Generated by Django 5.2.12 on 2026-06-08 21:01

import cms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_imagecollection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(upload_to=cms.utils.upload_image_carousel),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail_path',
            field=models.ImageField(upload_to=cms.utils.upload_image_collection, validators=[cms.utils.validate_image_format]),
        ),
    ]
