# Generated by Django 5.2.11 on 2026-04-20 17:10

import cms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_collection_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carrusel', 'verbose_name_plural': 'Carruseles'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Coleccion', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterModelOptions(
            name='imagecollection',
            options={'verbose_name': 'Imagen de coleccion', 'verbose_name_plural': 'Imagenes de colecciones'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail_path',
            field=models.ImageField(upload_to=cms.utils.upload_image_collection),
        ),
    ]
