# Generated by Django 5.2.11 on 2026-05-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_carousel_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['created_at'], 'verbose_name': 'Coleccion', 'verbose_name_plural': 'Colecciones'},
        ),
    ]
