# Generated by Django 5.2.14 on 2026-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_carousel_created_at_alter_carousel_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_es',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
