# Generated by Django 5.2.14 on 2026-05-28 03:18

import blog.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pieces', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('storage_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_es', models.CharField(max_length=255, null=True, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('slug_es', models.SlugField(null=True, unique=True)),
                ('slug_en', models.SlugField(null=True, unique=True)),
                ('content', models.TextField()),
                ('content_es', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('cover_image', models.ImageField(upload_to=blog.utils.upload_image_blog)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('pieces', models.ManyToManyField(blank=True, related_name='blogs', to='pieces.piece')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.section')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_status_published_idx')],
            },
        ),
    ]
