# Generated by Django 5.2.11 on 2026-03-04 18:17

import blog.utils
import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pieces', '0010_discount_name_piece_intro_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=254)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(upload_to=blog.utils.upload_image_blog)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('pieces', models.ManyToManyField(blank=True, related_name='blogs', to='pieces.piece')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
    ]
