# Generated by Django 5.2.12 on 2026-06-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug_es',
        ),
    ]
