# Generated by Django 5.2.11 on 2026-03-18 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_blog_title'),
        ('pieces', '0012_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pieces.section'),
            preserve_default=False,
        ),
    ]
