# Generated by Django 5.2.11 on 2026-04-20 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='storage_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
