# Generated by Django 5.2.14 on 2026-05-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_created_at_alter_blog_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_es',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
