"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from decouple import config

from pathlib import Path

#========================================== CARPETAS RELEVANTES ==========================================
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = 'static/'


#========================================== APPS INSTALADAS ==========================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #App del proyecto
    'users',
    'blog',
    'orders',
    'reviews',
    'pieces',
    'core',
    
]

#================================================= MIDDLEWARE ====================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


#================================================= DIRECCION DE LOS TEMPLATES(EN ESTE CASO SOLO LOS DE EMAILS) =================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


#================================================= CONFIG DATABSE =================================================
DATABASES = {
    'default': {
        'ENGINE': config('ENGINE_DB'),
        'NAME': config('NAME_DB'),      
        'USER': config('USER_DB'),             
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',  
        },
    }
}

#================================================= PASSWORD VALIDATORS =================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#================================================ JWT ==========================================================

#================================================ REST AUTH ==========================================================

#================================================ ALL AUTH ==========================================================

#================================================ REST_FRAMEWORK ======================================================

#================================================ EMAIL CONFIG ==========================================================

#================================================ COORS ==========================================================

#================================================ EXTRAS ==============================================

#================================================ LOGGING ======================================================

#================================================ SOCIAL PROVIDERS ======================================================

#================================================ CACHE ======================================================

#================================================ DOCUMENTACION SWAGGER ======================================================

#================================================ CONFIGURACION DE SENTRY ======================================================

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', cast=bool)
WSGI_APPLICATION = 'config.wsgi.application'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ALLOWED_HOSTS = []

ROOT_URLCONF = 'config.urls'

LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True