# Generated by Django 5.2.11 on 2026-02-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Ítem de Pedido', 'verbose_name_plural': 'Piezas del pedido'},
        ),
    ]
