# Generated by Django 5.2.11 on 2026-02-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_coupon_user_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingtracking',
            name='carrier',
            field=models.CharField(blank=True, choices=[('dhl', 'DHL'), ('ups', 'UPS'), ('fedex', 'FedEx')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingtracking',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
