# Generated by Django 5.2.11 on 2026-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_shippingtracking_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingtracking',
            name='carrier',
            field=models.CharField(choices=[('dhl', 'DHL'), ('ups', 'UPS'), ('fedex', 'FedEx')], default='dhl', max_length=50),
        ),
    ]
