# Generated by Django 5.2.11 on 2026-04-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_couponusage_coupon_alter_couponusage_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_mxn', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fetched_at', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
