# Generated by Django 5.2.11 on 2026-05-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_exchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Tipo de Cambio', 'verbose_name_plural': 'Tipos de Cambio'},
        ),
    ]
